name: CI

on: [push]

jobs:
  create_milestones_job:
    runs-on: ubuntu-latest
    name: Test Scheduled Milestones
    steps:
      - name: Checkout # To use as private action, you must check out the repository
        uses: actions/checkout@v2

      - name: Schedule Milestones
        uses: ./ # Use the action in the root directory
        id: scheduled
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Up for Review
          days: Tuesday,Thursday
          date_options: '{"month": "long", "day": "numeric"}'

      - name: Created Milestones
        run: echo ${{ steps.scheduled.outputs.milestones }}
